name: Scraping Automation

on:
  schedule:
    - cron: '0 */12 * * *'  # Cada 12 horas

jobs:
  run-scraping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Especifica la versión de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de tener un requirements.txt si usas dependencias

      - name: Run scraping script
        run: |
          python tu_script.py
